title: Aoran Chen
logo: /assets/img/aoranchen.JPG
description: Graduate Student @ UMass Amherst DACSS
#show_downloads: false
theme: jekyll-theme-minimal

linkedin: www.linkedin.com/in/aoran-chen-12b333385
email: aoranchen314@gmail.com
